UniversalTracker = UniversalTracker or {}

UniversalTracker.presets = {
    offBalance = {
	    id = -1,
        name = "Off Balance Preset",
        type = "Bar",
        targetType = "Reticle Target",
        listSettings = {
            columns = 1,
            horizontalOffsetScale = 1,
            verticalOffsetScale = 1,
        },
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
		    	accountName = true,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [1] = "39077",
            [2] = "45902",
            [3] = "2727",
            [4] = "120014",
            [5] = "23808",
            [6] = "20806",
            [7] = "34117",
            [8] = "25256",
            [9] = "34733",
            [10] = "34737",
            [11] = "130129",
            [12] = "130139",
            [13] = "130145",
            [14] = "125750",
            [15] = "131562",
            [16] = "62968",
            [17] = "62988",
            [18] = "137257",
            [19] = "45834",
            [20] = "137312",
            [21] = "134599",
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [39077] = true,
            [45902] = true,
            [2727] = true,
            [120014] = true,
            [23808] = true,
            [20806] = true,
            [34117] = true,
            [25256] = true,
            [34733] = true,
            [34737] = true,
            [130129] = true,
            [130139] = true,
            [130145] = true,
            [125750] = true,
            [131562] = true,
            [62968] = true,
            [62988] = true,
            [137257] = true,
            [45834] = true,
            [137312] = true,
            [134599] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,
    },
    stagger = {
	    id = -1,
        name = "Stagger Preset",
        type = "Compact",
        targetType = "Player",
        listSettings = {
            columns = 1,
            horizontalOffsetScale = 1,
            verticalOffsetScale = 1,
        },
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 0,
                y = 0,
                hidden = false,
		    	accountName = true,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [1] = "134336", -- stagger (target)
            [2] = "31816", -- stone giant (self)
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [134336] = true,
            [31816] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,

    },
    relentlessFocus = {
	    id = -1,
        name = "Relentless Focus Preset",
        type = "Compact",
        targetType = "Player",
        listSettings = {
            columns = 1,
            horizontalOffsetScale = 1,
            verticalOffsetScale = 1,
        },
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = true,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 0,
                y = 0,
                hidden = false,
		    	accountName = true,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [1] = "122587",
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [122587] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,
    },
    mercilessResolve = {
	    id = -1,
        name = "Merciless Resolve Preset",
        type = "Compact",
        targetType = "Player",
        listSettings = {
            columns = 1,
            horizontalOffsetScale = 1,
            verticalOffsetScale = 1,
        },
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = true,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 0,
                y = 0,
                hidden = false,
		    	accountName = true,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [1] = "122586",
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [122586] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,
    },
    alkosh = {
	    id = -1,
        name = "Alkosh Preset",
        type = "Bar",
        targetType = "Reticle Target",
        listSettings = {
            columns = 1,
            horizontalOffsetScale = 1,
            verticalOffsetScale = 1,
        },
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
		    	accountName = true,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [1] = "76667",
            [2] = "75753",
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [76667] = true,
            [75753] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,
    },
    mk = {
	    id = -1,
        name = "Martial Knowledge Preset",
        type = "Compact",
        targetType = "Reticle Target",
        listSettings = {
            columns = 1,
            horizontalOffsetScale = 1,
            verticalOffsetScale = 1,
        },
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 0,
                y = 0,
                hidden = false,
		    	accountName = true,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [1] = "127070",
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [127070] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,
    },
    ecShock = {
	    id = -1,
        name = "EC (Shock) Preset",
        type = "Compact",
        targetType = "Reticle Target",
        listSettings = {
            columns = 1,
            horizontalOffsetScale = 1,
            verticalOffsetScale = 1,
        },
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 0,
                y = 0,
                hidden = false,
		    	accountName = true,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [1] = "142653",
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [142653] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,
    },
    ecFire = {
	    id = -1,
        name = "EC (Fire) Preset",
        type = "Compact",
        targetType = "Reticle Target",
        listSettings = {
            columns = 1,
            horizontalOffsetScale = 1,
            verticalOffsetScale = 1,
        },
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 0,
                y = 0,
                hidden = false,
		    	accountName = true,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [1] = "142610",
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [142610] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,
    },
    ecIce = {
	    id = -1,
        name = "EC (Ice) Preset",
        type = "Compact",
        targetType = "Reticle Target",
        listSettings = {
            columns = 1,
            horizontalOffsetScale = 1,
            verticalOffsetScale = 1,
        },
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 0,
                y = 0,
                hidden = false,
		    	accountName = true,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [1] = "142652",
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [142652] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,
    },
    synergyCooldown = {
	    id = -1,
        name = "Resource Synergy Cooldown Preset",
        type = "Bar",
        targetType = "Player",
        listSettings = {
            columns = 1,
            horizontalOffsetScale = 1,
            verticalOffsetScale = 1,
        },
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 0.7,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
		    	accountName = true,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [1] = "48052",
            [2] = "85434",
            [3] = "63512",
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [48052] = true,
            [85434] = true,
            [63512] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,
    },
}