GET = GET or {}

GET.presets = {
    offBalance = {
	    id = -1,
        control = {
            object = nil,
            key = nil,
        },
        animation = {
            object = nil,
            key = nil,
        },
        name = "Off Balance Preset",
        type = "Bar",
        targetType = "Reticle Target",
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [0] = "39077",
            [1] = "45902",
            [2] = "2727",
            [3] = "120014",
            [4] = "23808",
            [5] = "20806",
            [6] = "34117",
            [7] = "25256",
            [8] = "34733",
            [9] = "34737",
            [10] = "130129",
            [11] = "130139",
            [12] = "130145",
            [13] = "125750",
            [14] = "131562",
            [15] = "62968",
            [16] = "62988",
            [17] = "137257",
            [18] = "45834",
            [19] = "137312",
            [20] = "134599",
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [39077] = true,
            [45902] = true,
            [2727] = true,
            [120014] = true,
            [23808] = true,
            [20806] = true,
            [34117] = true,
            [25256] = true,
            [34733] = true,
            [34737] = true,
            [130129] = true,
            [130139] = true,
            [130145] = true,
            [125750] = true,
            [131562] = true,
            [62968] = true,
            [62988] = true,
            [137257] = true,
            [45834] = true,
            [137312] = true,
            [134599] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,
    },
    stagger = {
	    id = -1,
        control = {
            object = nil,
            key = nil,
        },
        animation = {
            object = nil,
            key = nil,
        },
        name = "Stagger Preset",
        type = "Simple",
        targetType = "Player",
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [0] = "134336", -- stagger (target)
            [1] = "31816", -- stone giant (self)
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [134336] = true,
            [31816] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,

    },
    relentlessFocus = {
	    id = -1,
        control = {
            object = nil,
            key = nil,
        },
        animation = {
            object = nil,
            key = nil,
        },
        name = "Relentless Focus Preset",
        type = "Simple",
        targetType = "Player",
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = true,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [0] = "122587",
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [122587] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,
    },
    mercilessResolve = {
	    id = -1,
        control = {
            object = nil,
            key = nil,
        },
        animation = {
            object = nil,
            key = nil,
        },
        name = "Merciless Resolve Preset",
        type = "Simple",
        targetType = "Player",
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = true,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [0] = "122586",
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [122586] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,
    },
    alkosh = {
	    id = -1,
        control = {
            object = nil,
            key = nil,
        },
        animation = {
            object = nil,
            key = nil,
        },
        name = "Alkosh Preset",
        type = "Bar",
        targetType = "Reticle Target",
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [0] = "76667",
            [1] = "75753",
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [76667] = true,
            [75753] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,
    },
    mk = {
	    id = -1,
        control = {
            object = nil,
            key = nil,
        },
        animation = {
            object = nil,
            key = nil,
        },
        name = "Martial Knowledge Preset",
        type = "Simple",
        targetType = "Reticle Target",
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [0] = "127070",
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [127070] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,
    },
    synergyCooldown = {
	    id = -1,
        control = {
            object = nil,
            key = nil,
        },
        animation = {
            object = nil,
            key = nil,
        },
        name = "Resource Synergy Cooldown Preset",
        type = "Bar",
        targetType = "Player",
        textSettings = {
            duration = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            stacks = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = -5,
                y = 0,
                hidden = false,
            },
            abilityLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 0.7,
                x = 5,
                y = 0,
                hidden = false,
            },
            unitLabel = {
                color = {
                    r = 1,
                    g = 1,
                    b = 1,
                    a = 1,
                },
                textScale = 1,
                x = 5,
                y = 0,
                hidden = false,
            },
        },
        abilityIDs = { --abilityIDs are values. indexes increase by 1 from 0. Each setting gets an index.
            [0] = "48052",
        },
        hashedAbilityIDs = { --abilityIDs are keys
            [48052] = true,
        },
        overrideTexturePath = "",
        x = 0,
        y = 0,
        scale = 1,
        hidden = false,
    },
}